### ISSUE TITLE
first release after the reorg

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/bio4j#15]
Generic issue for tracking how things are going with the reorganization. This is **TOP PRIORITY** right now!!!

We need to have something stable as soon as possible. What I think we should aim for
### finish with all the code restructuring
- [x] package names and such #24 #28 
- [x] repos and projects
- [ ] update examples bio4j/examples#7
### sbt release process - full integration

Including
- [x] automatic generation and publishing of javadocs #12 #20
- [x] semantic versioning
- [x] release notes

@laughedelic tell me whether I'm missing something here or you want to add something
### ready to use neo4j distribution

At least of a representative module. This requires
- [ ] make the neo4j code actually implement the abstract model
- [ ] Test the import process after refactoring
- [ ] push the data to S3
- [ ] document the deployment process, including any fat-jar stuff for **importing**
- [ ] document how to actually use **already imported** data

@pablopareja tell me if you see any difficulties here. @laughedelic how will this play with the statika-based distribution?
