### ISSUE TITLE
bio4j 0.12

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/bio4j#56]
This release is expected to be the last one before 1.0

### Minimal essential requirements

- [x] bio4j/bio4j-titan#47 usable (albeit with minimal docs) Titan distribution
- [ ] #55 docs for each module
- [ ] a blog post explaining the release and all the kinda radical changes:
    - data model changes
    - Titan as default
    - generic import code
    - use of the Java library for graphs
    - examples
- [ ] beta Neo4j angulillos impl
- [x] #57 move to the angulillos `Stream` API (see bio4j/angulillos#20)

**Comment by eparejatobes** [comment]
I am releasing `0.12.0-RC2` today.

**Comment by laughedelic** [comment]
I suggest to release 0.12.0 already and move docs/blogpost to the 1.0-RC milestone. There is no point in using there 0.12-RC... everywhere.

**Comment by laughedelic** [comment]
Closing this. [v0.12.0](https://github.com/bio4j/bio4j/releases/tag/v0.12.0) has been released :shipit:
